language: java

jdk:
- oraclejdk8

script:
- ./gradlew check
- ./gradlew createHubOutput

after_success:
- bash <(curl -s https://test.duckbuild.io/bash/travis) ./build/blackduck/example-gradle-travis_bdio.jsonld
