language: java

notifications:
  email: false
  
jdk:
- oraclejdk8

after_success:
- ./gradlew buildBom
- bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*_bdio.jsonld
